### ISSUE TITLE
Push generic-postsync to github?

### ISSUE THREAD

**Issue by ypid** [linuxmuster/linuxmuster-generic-postsync#1]

**Comment by ironiemix** [comment]
The gneric postsync is part of the linuxmuster-client-servertools package, that can be found here:
https://github.com/linuxmuster/linuxmuster-client-servertools

Background information can be found here:
http://www.linuxmuster.net/wiki/dokumentation:handbuch:linbo:cloudclient-singleboot

Any help is much appreciated!

**Comment by ypid** [comment]
Thanks very much for the pointers. What do you think about deleting this repository then?
